### PR TITLE
run backtest using instrumentstatus

### PR DESCRIPTION
**Pull request by amitsinghpgs**

### CODE REVIEW

**Comment by amitsinghpgs** [comment]
Assuming you are running the test in codespace and you have successfully created the environment then to run the test you can do the following
1. create a catalog by running this driver file
`python historical_data/import_data/get_polygon_equity_data.py`
2. running the backtest by running the following driver file
`python historical_data/import_data/polygon_backtestengine.py`

backtest in step 2 will use the bar data from catalog created in step 1 and the statusupdate data will be directly loaded to backtest

**Comment by amitsinghpgs** [comment]
Assuming codespaces is being for testing then below are the steps to create python environment using poetry. 
1. Since we are using develop branch of nautilus for this PR you will need to clone that in codespaces while testing
```
cd ~
git clone --branch develop --depth 1 https://github.com/nautechsystems/nautilus_trader.git
```
2. install rust as thats needed for nautilus
```
curl https://sh.rustup.rs -sSf | sh
source $HOME/.cargo/env
```
3. go back to polygon_nautilus repo directory and run poetry install. This should create the python environment
`cd /workspaces/polygon_nautilus`
`poetry install`

**Review by Troubladore — CHANGES_REQUESTED** [review]
@amitsinghpgs - thanks for this contribution!

I'm seeing output like this from the embedded Nautilus catalog events:
2023-09-20T20:00:00.000000000Z [INF] BACKTESTER-1.PrintDataStrategy-000: InstrumentStatus(instrument_id=QQQ.XNAS, trading_session=Regular, status=CLOSED, halt_reason=NOT_HALTED, ts_event=1695240000000000000)

We updated the Session Names per below, along with some teaks to the Open/Close times. Can you take a look and update to match?

~~~~
Given the MarketHours data on 20230918 for QQQ from IBKR, we are assuming the following sessions would be created, [based on this information](https://www.nyse.com/markets/hours-calendars)
(all times are in US Eastern time zone)
(all times should be managed with nanosecond precision, to match NautilusTrader clock)

Session Name: NYSE Arca Early Trading
Pre-Open - 2:30am  (Trading Hours start minus 1.5 hours)
Open - 4:00am (Trading Hours start)
Close - 9:29:59.999999999 (Liquid Hours start minus 1 nanosecond)

Session Name: NYSE American Core Trading
Open - 9:30am (Liquid Hours start)
Close - 3:59:59.999999999 (Liquid Hours end minus 1 nanosecond)

Session Name: NYSE American Late Trading
Open - 4:00pm (Liquid Hours end)
Close - 8:00pm (Trading Hours end)

**Comment by amitsinghpgs** [comment]
> @amitsinghpgs - thanks for this contribution!
> 
> I'm seeing output like this from the embedded Nautilus catalog events: 2023-09-20T20:00:00.000000000Z [INF] BACKTESTER-1.PrintDataStrategy-000: InstrumentStatus(instrument_id=QQQ.XNAS, trading_session=Regular, status=CLOSED, halt_reason=NOT_HALTED, ts_event=1695240000000000000)
> 
> We updated the Session Names per below, along with some teaks to the Open/Close times. Can you take a look and update to match?
> 
> ```
> Given the MarketHours data on 20230918 for QQQ from IBKR, we are assuming the following sessions would be created, [based on this information](https://www.nyse.com/markets/hours-calendars)
> (all times are in US Eastern time zone)
> (all times should be managed with nanosecond precision, to match NautilusTrader clock)
> 
> Session Name: NYSE Arca Early Trading
> Pre-Open - 2:30am  (Trading Hours start minus 1.5 hours)
> Open - 4:00am (Trading Hours start)
> Close - 9:29:59.999999999 (Liquid Hours start minus 1 nanosecond)
> 
> Session Name: NYSE American Core Trading
> Open - 9:30am (Liquid Hours start)
> Close - 3:59:59.999999999 (Liquid Hours end minus 1 nanosecond)
> 
> Session Name: NYSE American Late Trading
> Open - 4:00pm (Liquid Hours end)
> Close - 8:00pm (Trading Hours end)
> ```

i see the session details  you have pasted here and I have created the instrumentstatus now to match the same. If you test the code again you should see the output along these lines:

2023-09-29T06:30:00.000000000Z [INF] BACKTESTER-1.PrintDataStrategy-000: InstrumentStatus(instrument_id=QQQ.XNAS, trading_session=**NYSE Arca Early Trading, status=PRE_OPEN**, halt_reason=NOT_HALTED, ts_event=1695969000000000000)
2023-09-29T08:00:00.000000000Z [INF] BACKTESTER-1.PrintDataStrategy-000: InstrumentStatus(instrument_id=QQQ.XNAS, trading_session=**NYSE Arca Early Trading, status=OPEN**, halt_reason=NOT_HALTED, ts_event=1695974400000000000)
2023-09-29T13:29:59.999999999Z [INF] BACKTESTER-1.PrintDataStrategy-000: InstrumentStatus(instrument_id=QQQ.XNAS, trading_session=**NYSE Arca Early Trading, status=CLOSED**, halt_reason=NOT_HALTED, ts_event=1695994199999999999)
2023-09-29T13:30:00.000000000Z [INF] BACKTESTER-1.PrintDataStrategy-000: InstrumentStatus(instrument_id=QQQ.XNAS, trading_session=**NYSE American Core Trading, status=OPEN,** halt_reason=NOT_HALTED, ts_event=1695994200000000000)
2023-09-29T19:59:59.999999999Z [INF] BACKTESTER-1.PrintDataStrategy-000: InstrumentStatus(instrument_id=QQQ.XNAS, trading_session=**NYSE American Core Trading, status=CLOSED**, halt_reason=NOT_HALTED, ts_event=1696017599999999999)
2023-09-29T20:00:00.000000000Z [INF] BACKTESTER-1.PrintDataStrategy-000: InstrumentStatus(instrument_id=QQQ.XNAS, trading_session=**NYSE American Late Trading, status=OPEN**, halt_reason=NOT_HALTED, ts_event=1696017600000000000)
2023-09-30T00:00:00.000000000Z [INF] BACKTESTER-1.PrintDataStrategy-000: InstrumentStatus(instrument_id=QQQ.XNAS, trading_session=**NYSE American Late Trading, status=CLOSED**, halt_reason=NOT_HALTED, ts_event=1696032000000000000)

The timestamps of the logs are in UTC so timestamp of 2023-09-29T06:30:00.000000000Z for early trading pre open means it happened at 2:30 am in EST as EST , UTC offset is 4 hrs.

**Review by Troubladore — APPROVED** [review]

**Comment by Troubladore** [comment]
Looks good, thank you for the updates @amitsinghpgs

**Pull request merged**
